trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DEV-ENV(adfed678-4682-4bb0-a62f-2ebd77f373fd)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t krishnaacr01.azurecr.io/web-game:tag 2048-game
      az acr login -n krishnaacr01
      docker push krishnaacr01.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'DEV-ENV(adfed678-4682-4bb0-a62f-2ebd77f373fd)'
    azureResourceGroup: 'RG-03'
    kubernetesCluster: 'testcluster1'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'DEV-ENV(adfed678-4682-4bb0-a62f-2ebd77f373fd)'
    azureContainerRegistry: 'krishnaacr01.azurecr.io'
    forceUpdate: false